const projects = [
  {
    title: 'Travelsdin - Le réseau social ultime pour les voyageurs',
    tags: [
      'JavaScript (ES6)',
      'MongoDB',
      'React.js',
      'Redux',
      'Rest API',
      'Node.js',
      'Live Chat',
      'Socket.io',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1662386727/ctivc99rxpjymdn0za1n.png',
    ],
    videoUrl: 'https://youtu.be/HUv5xN5qTS4',
    description:
      'Travelsdin est une plateforme sociale moderne conçue pour permettre aux voyageurs de se connecter, de partager leurs expériences et de planifier des aventures ensemble. Avec un système de messagerie en temps réel et une interface intuitive, elle révolutionne la manière dont les voyageurs interagissent en ligne.',
    linkDemo: 'https://travelsdin-express-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/Social-Network-Front-',
  },
  {
    title: 'Taskday - Gestion de projets intelligente et collaboration',
    tags: [
      'MongoDB',
      'JavaScript (ES6)',
      'Rest API',
      'Socket.io',
      'Vue.js',
      'SCSS',
      'Vuex',
      'MVC',
      'Single Page Application',
      'Drag and Drop',
      'Node.js',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1660916126/myPortfolio/qdtzolm9ldd5qlquq2aj.png',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=49DkbR-cJis',
    description:
      'Taskday est un système de gestion de projets intelligent qui améliore le travail en équipe grâce à des mises à jour en temps réel, un suivi des tâches et une interface de glisser-déposer conviviale. Conçu pour une efficacité et une productivité maximales.',
    linkDemo: 'https://taskday-monday-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/sprint-4',
  },
  {
    title: 'Chess Masters - Échecs multijoueurs avec chat en direct',
    tags: [
      'TypeScript',
      'React',
      'Redux Toolkit',
      'Node.js',
      'Live Chat',
      'MongoDB',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1668701783/myPortfolio/dg6pkn0oxvpgrtjn998y.png',
    ],
    videoUrl: 'https://youtu.be/I90vJUsZzFU',
    description:
      'Un jeu d’échecs multijoueurs interactif avec chat en direct et gameplay fluide. Conçu pour les amateurs d’échecs, il offre un environnement compétitif et captivant avec une interface élégante et réactive.',
    linkDemo: 'https://chess-v2-backend-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/Chess-V2-React',
  },
  {
    title: "AstroMind-AI - Assistant intelligent propulsé par l'IA",
    tags: [
      'AI',
      'Machine Learning',
      'React',
      'Vite',
      'TypeScript',
      'Node.js',
      'Express',
      'MongoDB',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1740232455/ax7kjnkrg75ptdatwvrf.png',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=Ypg4isxvXpk',
    description:
      "AstroMind-AI est un assistant de nouvelle génération propulsé par l'intelligence artificielle, qui s’intègre parfaitement aux modèles de machine learning pour augmenter la productivité, automatiser les flux de travail et fournir des analyses approfondies en temps réel.",
    linkDemo: 'https://astromind-ai.up.railway.app/#/',
    linkGitHub: 'https://github.com/shlomiNugarker/AstroMind-AI',
  },
  {
    title: 'Tetris - Jeu classique en TypeScript',
    tags: [
      'Game Development',
      'TypeScript',
      'Canvas API',
      'Vite',
      'Vanilla JavaScript',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741333933/hcft00ztvoddagepecqd.jpg',
    ],
    videoUrl: '',
    description:
      'Un jeu Tetris moderne et léger, construit avec TypeScript et la Canvas API. Le jeu se caractérise par des animations fluides, un ajustement dynamique de la difficulté et une interface utilisateur épurée.',
    linkDemo: 'https://shlominugarker.github.io/tetris-vannila-ts/',
    linkGitHub: 'https://github.com/shlomiNugarker/tetris-vannila-ts',
  },
  {
    title: 'Todo List - Application de gestion de tâches',
    tags: [
      'Task Management',
      'React',
      'Vite',
      'TypeScript',
      'Tailwind CSS',
      'LocalStorage',
      'State Management',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741334749/m7tjy3w64of8myg4zzhf.jpg',
    ],
    videoUrl: '',
    description:
      'Une application moderne et efficace de liste de tâches, développée avec React et TypeScript. L’application permet de créer, modifier et filtrer les tâches par assigné et par priorité, tout en sauvegardant les données localement.',
    linkDemo: 'https://shlominugarker.github.io/todo-list-react-application/',
    linkGitHub: 'https://github.com/shlomiNugarker/todo-list-react-application',
  },
  {
    title: 'Jpeg-to-PDF - Convertir des images en PDF avec OCR',
    tags: [
      'OCR',
      'Image Processing',
      'React',
      'Next.js',
      'Tailwind CSS',
      'TypeScript',
      'Node.js',
      'Express',
      'Tesseract.js',
      'pdf-lib',
      'MongoDB',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741335295/q9yen9arwacqz2l1m7if.jpg',
    ],
    videoUrl: '',
    description:
      'Jpeg-to-PDF est une application web avancée permettant de convertir des images en fichiers PDF. Elle supporte la technologie OCR via Tesseract.js, ce qui permet d’extraire le texte des images et de l’intégrer dans le PDF généré. Construit avec Next.js pour le frontend et Node.js avec Express pour le backend, il permet aux utilisateurs de charger des images, de les convertir en PDF de haute qualité et de télécharger le résultat sans effort.',
    features: [
      '💡 Conversion rapide et efficace d’images en PDF',
      '🔍 Support OCR pour extraire le texte des images',
      '📤 Interface conviviale pour le chargement des images',
      '📥 Téléchargement du fichier PDF généré',
      '🗑️ Nettoyage automatique des fichiers temporaires après traitement',
      '🚀 Frontend moderne avec Next.js et Tailwind CSS',
      '⚙️ Backend robuste avec Express et MongoDB',
    ],
    linkDemo: 'https://image-to-pdf-free.vercel.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/jpeg-to-pdf-nextjs',
  },
  {
    title: 'WhatsApp Clone - Application de chat en temps réel',
    tags: [
      'Real-time Communication',
      'Chat Application',
      'Angular',
      'TypeScript',
      'SCSS',
      'Node.js',
      'Express',
      'MongoDB',
      'Socket.io',
      'JWT Authentication',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741336608/mrx5om1pnkozrla5bpsm.jpg',
    ],
    videoUrl: '',
    description:
      'WhatsApp Clone est une application de chat complète qui reproduit les fonctionnalités de base de WhatsApp, permettant la messagerie en temps réel entre utilisateurs. Développée avec Angular pour le frontend et Node.js avec Express pour le backend, elle utilise MongoDB pour le stockage des données et Socket.io pour les mises à jour en temps réel. L’application inclut l’authentification des utilisateurs, le cryptage des messages et une interface de chat intuitive.',
    features: [
      '💡 Communication sécurisée et en temps réel avec Socket.io',
      '🔐 Authentification des utilisateurs avec JWT',
      '📤 Système d’inscription et de connexion fluide',
      '📥 Stockage de l’historique des chats et des données via MongoDB',
      '🎨 Interface moderne développée avec Angular et SCSS',
      '🚀 Backend scalable et performant avec Express.js',
      '🗑️ Nettoyage automatique des logs temporaires de chat',
    ],
    linkDemo: 'https://achchhapp.onrender.com/',
    linkGitHub: 'https://github.com/shlomiNugarker/whatsapp-clone-angular',
  },
  {
    title: 'Snake Game - Jeu classique de navigateur "Snake"',
    tags: [
      'Web Game',
      'JavaScript',
      'HTML',
      'CSS',
      'Vanilla JS',
      'Game Development',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741336903/hwdhzecww9joudezoyrn.jpg',
    ],
    videoUrl: '',
    description:
      'Un jeu classique de Snake, développé avec du JavaScript pur (Vanilla JS) et jouable directement dans le navigateur. Le joueur contrôle le serpent à l’aide des touches fléchées, en essayant de manger le maximum de nourriture sans heurter les bords de l’écran ou se mordre lui-même. Le jeu inclut un système de points, des effets sonores et une accélération progressive à mesure que le serpent grandit.',
    features: [
      '🎮 Expérience de jeu classique de Snake',
      '⌨️ Contrôle via les touches fléchées pour une jouabilité fluide',
      '🔊 Effets sonores pour le mouvement et la consommation de nourriture',
      '📈 Suivi des points en temps réel',
      '🚀 Code léger et extensible en Vanilla JS',
      '🎨 Style CSS simple pour une interface épurée',
    ],
    linkDemo: 'https://shlominugarker.github.io/snake-vannila-js/',
    linkGitHub: 'http://github.com/shlomiNugarker/snake-vannila-js',
  },
  {
    title: 'Checkers Game - Jeu de dames classique basé sur Vue.js',
    tags: [
      'Web Game',
      'Vue.js',
      'TypeScript',
      'Vite',
      'CSS',
      'Game Development',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741337246/gxxqlgeuaqbk67qrdhge.jpg',
    ],
    videoUrl: '',
    description:
      'Un jeu de dames classique développé avec Vue.js et TypeScript, doté d’une interface moderne et respectant entièrement les règles standard du jeu.',
    features: [
      '🎮 Jeu de dames interactif avec une interface intuitive',
      '🔄 Mode deux joueurs pour des parties compétitives',
      '🎨 Interface moderne développée avec Vue.js',
      '🖱️ Expérience utilisateur fluide avec animations',
      '📈 Suivi des points et historique des coups',
      '🚀 Optimisé avec Vite pour un chargement rapide et des performances élevées',
    ],
    linkDemo: 'https://shlominugarker.github.io/checkers-vue-js/',
    linkGitHub: 'https://github.com/shlomiNugarker/checkers-vue-js',
  },
  {
    title: 'Sudoku Game - Jeu web avancé en TypeScript',
    tags: [
      'Web Game',
      'TypeScript',
      'HTML',
      'CSS',
      'Vite',
      'Game Development',
      'Local Storage',
      'Algorithmic Optimization',
      'OOP',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741337655/szym9lrspw75mtysoya2.jpg',
    ],
    videoUrl: '',
    description:
      'Un jeu de Sudoku riche en fonctionnalités, développé avec TypeScript et optimisé pour une jouabilité rapide et fluide dans le navigateur. Le jeu inclut une validation en temps réel des mouvements, la génération dynamique de grilles, le choix du niveau de difficulté et une interface élégante et moderne. Implémenté selon des principes de programmation orientée objet, il garantit une architecture évolutive et performante. La progression est automatiquement sauvegardée dans le Local Storage, permettant aux joueurs de reprendre leur partie à tout moment.',
    features: [
      '🎮 Jouabilité interactive et dynamique de Sudoku',
      '🔢 Génération intelligente de grilles avec niveaux de difficulté ajustables',
      '✔️ Validation des mouvements en temps réel',
      '💾 Sauvegarde automatique de la progression via Local Storage',
      '📊 Plusieurs niveaux de difficulté : Facile, Moyen, Difficile, Expert',
      '⚡ Performance optimisée avec Vite pour un chargement rapide',
      '🖥️ Design responsive avec grille adaptative',
      '🎨 Interface élégante avec thèmes personnalisables (clair et sombre)',
      '🚀 Architecture évolutive utilisant TypeScript et principes OOP',
    ],
    linkDemo: 'https://shlominugarker.github.io/sudoku-vannila-ts/',
    linkGitHub: 'https://github.com/shlomiNugarker/sudoku-vannila-ts',
  },
  {
    title: '2D Action Game - Développement de jeux en TypeScript',
    tags: [
      'Game Development',
      'TypeScript',
      'Canvas',
      'Web Game',
      'Webpack',
      'Object-Oriented Programming',
      'Animations',
      'Physics',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741337983/fyerm3gsrfvkzdungm6j.jpg',
    ],
    videoUrl: '',
    description:
      "Un jeu d’action 2D à grande vitesse, développé avec TypeScript et conçu pour être exécuté directement dans le navigateur. Le jeu propose un personnage contrôlé par le joueur, capable de se déplacer, de sauter et d'attaquer des ennemis. Grâce à des interactions physiques avancées, des animations de collision et des effets de fond en couches, il démontre les techniques de pointe du développement de jeux utilisant JavaScript moderne et les principes OOP.",
    features: [
      '🎮 Gameplay d’action 2D dynamique avec contrôle total du joueur',
      '🕹️ Contrôle via le clavier avec physique en temps réel',
      '👾 Système avancé d’IA pour les ennemis avec différents schémas d’attaque',
      '💥 Détection de collisions et effets visuels basés sur des particules',
      '🖥️ Arrière-plans en couches avec effet parallax pour une immersion totale',
      '⚡ Boucle de jeu optimisée pour des performances fluides',
      '🎨 Sprites animés pour le joueur et les ennemis',
      '🚀 Architecture modulaire et évolutive utilisant TypeScript et OOP',
    ],
    linkDemo: 'https://shlominugarker.github.io/game-development-tutorial/',
    linkGitHub: 'https://github.com/shlomiNugarker/game-development-tutorial',
  },
  {
    title: 'Minesweeper - Le classique Minesweeper en JavaScript',
    tags: [
      'Web Game',
      'JavaScript',
      'HTML',
      'CSS',
      'Game Development',
      'Algorithms',
      'UI/UX',
      'Animations',
      'Audio Effects',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741338893/noxnpv9mpekeoyilpibj.jpg',
    ],
    videoUrl: '',
    description:
      'Une version modernisée du jeu classique Minesweeper, développée avec JavaScript, HTML et CSS. Le jeu offre une génération dynamique des grilles, des mécanismes intelligents pour révéler les cellules, le marquage des mines ainsi que des conditions de victoire et de défaite, et des effets sonores interactifs pour améliorer l’expérience de jeu.',
    features: [
      '🎮 Gameplay classique de Minesweeper avec un design moderne',
      '🛠️ Taille de grille et niveaux de difficulté personnalisables',
      '🔍 Mécanisme intelligent pour révéler les cellules et détecter les zones vides',
      '🚩 Système de marquage pour identifier les mines suspectes',
      '🎵 Effets sonores interactifs pour une immersion totale',
      '⏳ Minuteur en temps réel pour suivre la durée du jeu',
      '⚡ Animations fluides et design responsive',
      '🚀 Logique de jeu optimisée pour des performances rapides',
    ],
    linkDemo: 'https://shlominugarker.github.io/minesweeper-sprint-1/',
    linkGitHub: 'https://github.com/shlomiNugarker/minesweeper-sprint-1',
  },
  {
    title: 'Remote Sessions - Plateforme de collaboration de code en direct',
    tags: [
      'Web Application',
      'React',
      'TypeScript',
      'Node.js',
      'Express',
      'MongoDB',
      'WebSockets',
      'JWT Authentication',
      'Real-Time Collaboration',
      'Code Editor',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1673381405/myPortfolio/cztl69dtpc1xxt5j6sf0.png',
    ],
    videoUrl: '',
    description:
      'Remote Sessions est une plateforme web qui permet la collaboration sur le code en temps réel ainsi que des sessions de programmation à distance. Plusieurs utilisateurs peuvent éditer simultanément le code, avec des mises à jour en direct via WebSockets. Construit avec React et TypeScript pour le frontend, et Node.js avec Express et MongoDB pour le backend, il offre une expérience fluide pour le développement collaboratif.',
    features: [
      '💻 Édition collaborative de code en temps réel',
      '🔐 Authentification sécurisée des utilisateurs avec JWT',
      '⚡ Mises à jour instantanées via WebSockets',
      '📁 Architecture REST API modulaire',
      '🗄️ Stockage efficace des données avec MongoDB',
      '🚀 Interface moderne développée avec React et TypeScript',
      '🔄 Gestion d’état transparente avec custom hooks',
      '🎨 Design entièrement responsive pour tous les appareils',
    ],
    linkDemo: 'https://remote-sessions-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/remote-sessions-react',
  },
  {
    title: 'Monopoly - Jeu de société numérique basé sur Vue.js',
    tags: [
      'Web Game',
      'Vue.js',
      'Vite',
      'JavaScript',
      'Game Development',
      'WebSockets',
      'State Management',
      'UI/UX',
      'Multiplayer',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1661077030/myPortfolio/ypvbcwolwot13zpj83m1.png',
    ],
    videoUrl: '',
    description:
      'Monopoly est une adaptation numérique moderne du jeu de société classique Monopoly, développée avec Vue.js et Vite. Le jeu supporte le multijoueur en temps réel via WebSockets, propose des modaux interactifs, une gestion dynamique du plateau et des éléments d’interface responsives. Les joueurs peuvent acheter des propriétés, échanger des actifs et s’affronter dans une expérience numérique immersive.',
    features: [
      '🎲 Jeu de Monopoly entièrement interactif',
      '🌐 Support multijoueur via WebSockets',
      '🛠️ Gestion dynamique du plateau avec administration personnalisée des cases',
      '💳 Cartes de propriété et transactions entre joueurs',
      '📊 Gestion d’état fluide avec Vuex',
      '⚡ Performances rapides grâce à Vite et un rendu optimisé',
      '🎨 Design moderne et responsive',
      '🔄 Mises à jour en direct pour les mouvements et événements des joueurs',
    ],
    linkDemo: 'https://github.com/shlomiNugarker/monoploly-vue.js',
    linkGitHub: 'https://github.com/shlomiNugarker/monopoly-demo/#/',
  },
  {
    title:
      'Ultimate Meme Generator - Application web ultime pour créer des mèmes',
    tags: [
      'Web Application',
      'JavaScript',
      'HTML',
      'CSS',
      'Canvas',
      'Image Processing',
      'UI/UX',
      'Local Storage',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741339981/myPortfolio/b5ot6xjlgir4baq0fz62.jpg',
    ],
    videoUrl: '',
    description:
      'Ultimate Meme Generator est une application web qui permet aux utilisateurs de créer et personnaliser des mèmes facilement. Les utilisateurs peuvent sélectionner une image dans une large galerie, ajouter plusieurs couches de texte, ajuster les styles et télécharger leurs créations sous forme d’images. L’application prend également en charge l’enregistrement des projets dans le Local Storage pour des modifications ultérieures.',
    features: [
      '🖼️ Large galerie d’images pour mèmes',
      '✏️ Plusieurs couches de texte personnalisables',
      '📏 Ajustement de la taille, de la position et de l’alignement du texte',
      '💾 Sauvegarde des projets de mèmes dans le Local Storage',
      '📥 Téléchargement des mèmes au format image',
      '🎨 Interface utilisateur intuitive et responsive',
      '⚡ Rendu optimisé grâce à l’API Canvas de HTML',
    ],
    linkDemo:
      'https://shlominugarker.github.io/ultimate-meme-generator-sprint-2/',
    linkGitHub:
      'https://github.com/shlomiNugarker/ultimate-meme-generator-sprint-2',
  },
  {
    title: 'Système CMS personnalisé avec Next.js',
    tags: [
      'Next.js',
      'TypeScript',
      'PostgreSQL',
      'Drizzle ORM',
      'Tailwind CSS',
      'NextAuth.js',
      'Cloudinary',
      'Docker',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741512665/myPortfolio/40f5fc4f-5a40-49d1-b070-9652e9e73d75.png',
    ],
    videoUrl: '',
    description:
      "Un système CMS dynamique développé avec Next.js et Drizzle ORM. Il permet la gestion des pages, l'édition de contenu via une interface d'administration flexible et le stockage des médias sur Cloudinary.",
    linkDemo: 'https://my-site-data-api.vercel.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/nextjs-with-costum-cms',
    features: [
      'Gestion dynamique du contenu basée sur des tables',
      'Authentification des utilisateurs avec NextAuth',
      "Interface d'administration interactive avec Tailwind CSS",
      'Gestion des fichiers multimédias avec Cloudinary',
      'Prise en charge du déploiement avec Docker',
      'Gestion des données via une API REST',
    ],
  },
]

const projectsWithDynamicIds = projects.map((project, index) => ({
  id: index + 1,
  ...project,
}))

export default projectsWithDynamicIds
