const projects = [
  {
    title: 'Travelsdin - La red social definitiva para viajeros',
    tags: [
      'JavaScript (ES6)',
      'MongoDB',
      'React.js',
      'Redux',
      'Rest API',
      'Node.js',
      'Live Chat',
      'Socket.io',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1662386727/ctivc99rxpjymdn0za1n.png',
    ],
    videoUrl: 'https://youtu.be/HUv5xN5qTS4',
    description:
      'Travelsdin es una plataforma social moderna diseñada para que los viajeros se conecten, compartan experiencias y planifiquen aventuras juntos. Con mensajería en tiempo real y una interfaz intuitiva, revoluciona la forma en que los viajeros interactúan en línea.',
    linkDemo: 'https://travelsdin-express-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/Social-Network-Front-',
  },
  {
    title: 'Taskday - Gestión de proyectos inteligente y colaboración',
    tags: [
      'MongoDB',
      'JavaScript (ES6)',
      'Rest API',
      'Socket.io',
      'Vue.js',
      'SCSS',
      'Vuex',
      'MVC',
      'Single Page Application',
      'Drag and Drop',
      'Node.js',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1660916126/myPortfolio/qdtzolm9ldd5qlquq2aj.png',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=49DkbR-cJis',
    description:
      'Taskday es un sistema inteligente de gestión de proyectos que mejora el trabajo en equipo mediante actualizaciones en tiempo real, seguimiento de tareas y una interfaz de arrastrar y soltar fácil de usar. Diseñado para la máxima eficiencia y productividad.',
    linkDemo: 'https://taskday-monday-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/sprint-4',
  },
  {
    title: 'Chess Masters - Ajedrez multijugador con chat en vivo',
    tags: [
      'TypeScript',
      'React',
      'Redux Toolkit',
      'Node.js',
      'Live Chat',
      'MongoDB',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1668701783/myPortfolio/dg6pkn0oxvpgrtjn998y.png',
    ],
    videoUrl: 'https://youtu.be/I90vJUsZzFU',
    description:
      'Un juego de ajedrez multijugador interactivo con chat en tiempo real y jugabilidad fluida. Diseñado para los entusiastas del ajedrez, ofrece un entorno competitivo y atractivo con una interfaz elegante y responsiva.',
    linkDemo: 'https://chess-v2-backend-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/Chess-V2-React',
  },
  {
    title: 'AstroMind-AI - Asistente inteligente impulsado por AI',
    tags: [
      'React',
      'Vite',
      'Node.js',
      'TypeScript',
      'JWT',
      'OpenAI API',
      'MongoDB',
      'Tailwind CSS',
    ],

    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1740232455/ax7kjnkrg75ptdatwvrf.png',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=Ypg4isxvXpk',
    description:
      'AstroMind-AI es un asistente de nueva generación potenciado por inteligencia artificial que se integra a la perfección con modelos de machine learning para aumentar la productividad, automatizar flujos de trabajo y proporcionar análisis profundos en tiempo real.',
    features: [
      '🔹 Integration with OpenAI API for AI-generated astrological insights',
      '🔹 Advanced user authentication system with JWT',
      '🔹 Multilingual support (Hebrew & English) using i18n',
      '🔹 Smart chatbot with real-time interaction and responsive UI',
      '🔹 Secure connection to MongoDB database',
      '🔹 Modern user interface built with React and Tailwind CSS',
      '🔹 Data security with advanced role-based access control',
      '🔹 User management with different access levels (Admin / User)',
    ],
    linkDemo: 'https://astromind-ai.up.railway.app/#/',
    linkGitHub: 'https://github.com/shlomiNugarker/AstroMind-AI',
  },
  {
    title: 'Tetris - Juego clásico en TypeScript',
    tags: [
      'Game Development',
      'TypeScript',
      'Canvas API',
      'Vite',
      'Vanilla JavaScript',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741333933/hcft00ztvoddagepecqd.jpg',
    ],
    videoUrl: '',
    description:
      'Un juego Tetris moderno y liviano construido con TypeScript y la Canvas API. El juego cuenta con animaciones suaves, ajuste dinámico de dificultad y una interfaz de usuario limpia.',
    linkDemo: 'https://shlominugarker.github.io/tetris-vannila-ts/',
    linkGitHub: 'https://github.com/shlomiNugarker/tetris-vannila-ts',
  },
  {
    title: 'Todo List - Aplicación de gestión de tareas',
    tags: [
      'Task Management',
      'React',
      'Vite',
      'TypeScript',
      'Tailwind CSS',
      'LocalStorage',
      'State Management',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741334749/m7tjy3w64of8myg4zzhf.jpg',
    ],
    videoUrl: '',
    description:
      'Una aplicación moderna y eficiente de lista de tareas desarrollada con React y TypeScript. La aplicación permite crear, editar y filtrar tareas por asignado y prioridad, y guarda los datos de forma local.',
    linkDemo: 'https://shlominugarker.github.io/todo-list-react-application/',
    linkGitHub: 'https://github.com/shlomiNugarker/todo-list-react-application',
  },
  {
    title: 'Jpeg-to-PDF - Convertir imágenes a PDF con OCR',
    tags: [
      'OCR',
      'Image Processing',
      'React',
      'Next.js',
      'Tailwind CSS',
      'TypeScript',
      'Node.js',
      'Express',
      'Tesseract.js',
      'pdf-lib',
      'MongoDB',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741335295/q9yen9arwacqz2l1m7if.jpg',
    ],
    videoUrl: '',
    description:
      'Jpeg-to-PDF es una aplicación web avanzada para convertir imágenes en archivos PDF. Soporta tecnología OCR a través de Tesseract.js, lo que permite extraer texto de las imágenes e incorporarlo en el PDF generado. Construida con Next.js en el frontend y Node.js con Express en el backend, permite a los usuarios cargar imágenes, convertirlas en PDFs de alta calidad y descargarlos sin problemas.',
    features: [
      '💡 Conversión rápida y eficiente de imágenes a PDF',
      '🔍 Soporte OCR para extraer texto de las imágenes',
      '📤 Interfaz amigable para la carga de imágenes',
      '📥 Descarga del archivo PDF generado',
      '🗑️ Limpieza automática de archivos temporales tras el procesamiento',
      '🚀 Frontend moderno con Next.js y Tailwind CSS',
      '⚙️ Backend robusto con Express y MongoDB',
    ],
    linkDemo: 'https://image-to-pdf-free.vercel.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/jpeg-to-pdf-nextjs',
  },
  {
    title: 'WhatsApp Clone - Aplicación de chat en tiempo real',
    tags: [
      'Real-time Communication',
      'Chat Application',
      'Angular',
      'TypeScript',
      'SCSS',
      'Node.js',
      'Express',
      'MongoDB',
      'Socket.io',
      'JWT Authentication',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741336608/mrx5om1pnkozrla5bpsm.jpg',
    ],
    videoUrl: '',
    description:
      'WhatsApp Clone es una aplicación de chat completa que replica las funcionalidades básicas de WhatsApp, permitiendo la mensajería en tiempo real entre usuarios. Construida con Angular en el frontend y Node.js con Express en el backend, utiliza MongoDB para el almacenamiento de datos y Socket.io para actualizaciones en tiempo real. La aplicación incluye autenticación de usuario, cifrado de mensajes y una interfaz de chat intuitiva.',
    features: [
      '💡 Comunicación segura y en tiempo real con Socket.io',
      '🔐 Autenticación de usuario con JWT',
      '📤 Registro e inicio de sesión sin problemas',
      '📥 Almacenamiento del historial de chat y datos de usuarios en MongoDB',
      '🎨 Interfaz moderna desarrollada con Angular y SCSS',
      '🚀 Backend escalable y eficiente con Express.js',
      '🗑️ Limpieza automática de logs temporales de chat',
    ],
    linkDemo: 'https://achchhapp.onrender.com/',
    linkGitHub: 'https://github.com/shlomiNugarker/whatsapp-clone-angular',
  },
  {
    title: 'Snake Game - Juego clásico de navegador "Snake"',
    tags: [
      'Web Game',
      'JavaScript',
      'HTML',
      'CSS',
      'Vanilla JS',
      'Game Development',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741336903/hwdhzecww9joudezoyrn.jpg',
    ],
    videoUrl: '',
    description:
      'Un juego clásico de Snake construido con JavaScript puro (Vanilla JS) y jugable directamente en el navegador. El jugador controla la serpiente usando las flechas del teclado, tratando de comer la mayor cantidad de comida posible sin chocar contra los bordes de la pantalla o contra sí misma. El juego incluye un sistema de puntuación, efectos de sonido y aumento de velocidad a medida que la serpiente crece.',
    features: [
      '🎮 Experiencia clásica de juego Snake',
      '⌨️ Control con flechas para una jugabilidad fluida',
      '🔊 Efectos de sonido para el movimiento y el consumo de comida',
      '📈 Seguimiento de puntos en tiempo real',
      '🚀 Código ligero y escalable en Vanilla JS',
      '🎨 Estilo CSS sencillo para una experiencia limpia',
    ],
    linkDemo: 'https://shlominugarker.github.io/snake-vannila-js/',
    linkGitHub: 'http://github.com/shlomiNugarker/snake-vannila-js',
  },
  {
    title: 'Checkers Game - Juego clásico de damas basado en Vue.js',
    tags: [
      'Web Game',
      'Vue.js',
      'TypeScript',
      'Vite',
      'CSS',
      'Game Development',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741337246/gxxqlgeuaqbk67qrdhge.jpg',
    ],
    videoUrl: '',
    description:
      'Un juego clásico de damas construido con Vue.js y TypeScript, con una interfaz moderna y total adherencia a las reglas estándar del juego.',
    features: [
      '🎮 Juego interactivo de damas con interfaz intuitiva',
      '🔄 Modo para dos jugadores para un juego competitivo',
      '🎨 Interfaz moderna desarrollada con Vue.js',
      '🖱️ Experiencia de usuario fluida con animaciones',
      '📈 Seguimiento de puntos e historial de movimientos',
      '🚀 Optimizado con Vite para carga rápida y alto rendimiento',
    ],
    linkDemo: 'https://shlominugarker.github.io/checkers-vue-js/',
    linkGitHub: 'https://github.com/shlomiNugarker/checkers-vue-js',
  },
  {
    title: 'Sudoku Game - Juego web avanzado en TypeScript',
    tags: [
      'Web Game',
      'TypeScript',
      'HTML',
      'CSS',
      'Vite',
      'Game Development',
      'Local Storage',
      'Algorithmic Optimization',
      'OOP',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741337655/szym9lrspw75mtysoya2.jpg',
    ],
    videoUrl: '',
    description:
      'Un juego de Sudoku repleto de funciones, desarrollado con TypeScript y optimizado para una jugabilidad rápida y fluida en el navegador. El juego incluye validación de movimientos en tiempo real, generación dinámica de puzzles, selección de nivel de dificultad y una interfaz elegante y moderna. Implementado utilizando principios de programación orientada a objetos, garantiza una arquitectura escalable y eficiente. El progreso se guarda automáticamente en Local Storage, permitiendo a los jugadores reanudar su juego en cualquier momento.',
    features: [
      '🎮 Jugabilidad interactiva y dinámica de Sudoku',
      '🔢 Generación inteligente del tablero con niveles de dificultad ajustables',
      '✔️ Validación de movimientos en tiempo real',
      '💾 Guardado automático del progreso en Local Storage',
      '📊 Múltiples niveles de dificultad: Fácil, Medio, Difícil, Experto',
      '⚡ Rendimiento optimizado con Vite para carga rápida',
      '🖥️ Diseño responsivo con una cuadrícula adaptable',
      '🎨 Interfaz elegante con temas personalizables (claro y oscuro)',
      '🚀 Arquitectura escalable usando TypeScript y principios de OOP',
    ],
    linkDemo: 'https://shlominugarker.github.io/sudoku-vannila-ts/',
    linkGitHub: 'https://github.com/shlomiNugarker/sudoku-vannila-ts',
  },
  {
    title: '2D Action Game - Desarrollo de juegos en TypeScript',
    tags: [
      'Game Development',
      'TypeScript',
      'Canvas',
      'Web Game',
      'Webpack',
      'Object-Oriented Programming',
      'Animations',
      'Physics',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741337983/fyerm3gsrfvkzdungm6j.jpg',
    ],
    videoUrl: '',
    description:
      'Un juego de acción 2D de ritmo rápido, desarrollado con TypeScript y diseñado para ejecutarse directamente en el navegador. El juego presenta un personaje controlado por el jugador que puede moverse, saltar y atacar a enemigos. Con interacciones físicas avanzadas, animaciones de colisión y efectos de fondo en capas, muestra técnicas de desarrollo de juegos de vanguardia utilizando JavaScript moderno y principios de OOP.',
    features: [
      '🎮 Jugabilidad dinámica de acción 2D con control total del jugador',
      '🕹️ Movimiento controlado por teclado con física en tiempo real',
      '👾 Sistema avanzado de IA para enemigos con patrones de ataque variados',
      '💥 Detección de colisiones y efectos visuales basados en partículas',
      '🖥️ Fondos en capas con efecto parallax para una experiencia inmersiva',
      '⚡ Ciclo de juego optimizado para un rendimiento fluido',
      '🎨 Sprites animados tanto para el jugador como para los enemigos',
      '🚀 Arquitectura escalable y modular usando TypeScript y OOP',
    ],
    linkDemo: 'https://shlominugarker.github.io/game-development-tutorial/',
    linkGitHub: 'https://github.com/shlomiNugarker/game-development-tutorial',
  },
  {
    title: 'Minesweeper - El clásico juego Minesweeper en JavaScript',
    tags: [
      'Web Game',
      'JavaScript',
      'HTML',
      'CSS',
      'Game Development',
      'Algorithms',
      'UI/UX',
      'Animations',
      'Audio Effects',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741338893/noxnpv9mpekeoyilpibj.jpg',
    ],
    videoUrl: '',
    description:
      'Una versión modernizada del clásico juego Minesweeper, desarrollada con JavaScript, HTML y CSS. Ofrece generación dinámica de tableros, mecanismos inteligentes para revelar celdas, marcado de minas, condiciones de victoria y derrota, y efectos de sonido interactivos para mejorar la experiencia de juego.',
    features: [
      '🎮 Jugabilidad clásica de Minesweeper con un diseño moderno',
      '🛠️ Tamaño de tablero y niveles de dificultad personalizables',
      '🔍 Mecanismo inteligente para revelar celdas y descubrir áreas vacías',
      '🚩 Sistema de marcación para identificar minas sospechosas',
      '🎵 Efectos de sonido interactivos para una experiencia envolvente',
      '⏳ Temporizador en tiempo real para seguir la duración del juego',
      '⚡ Animaciones fluidas y diseño responsivo',
      '🚀 Lógica de juego optimizada para un rendimiento rápido',
    ],
    linkDemo: 'https://shlominugarker.github.io/minesweeper-sprint-1/',
    linkGitHub: 'https://github.com/shlomiNugarker/minesweeper-sprint-1',
  },
  {
    title: 'Remote Sessions - Plataforma de colaboración de código en vivo',
    tags: [
      'Web Application',
      'React',
      'TypeScript',
      'Node.js',
      'Express',
      'MongoDB',
      'WebSockets',
      'JWT Authentication',
      'Real-Time Collaboration',
      'Code Editor',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1673381405/myPortfolio/cztl69dtpc1xxt5j6sf0.png',
    ],
    videoUrl: '',
    description:
      'Remote Sessions es una plataforma web que permite la colaboración en código en tiempo real y sesiones de programación remota. Varios usuarios pueden editar código simultáneamente, con actualizaciones en vivo gracias a WebSockets. Construida con React y TypeScript en el frontend y Node.js con Express y MongoDB en el backend, ofrece una experiencia fluida para el desarrollo colaborativo.',
    features: [
      '💻 Edición colaborativa de código en tiempo real',
      '🔐 Autenticación segura de usuarios con JWT',
      '⚡ Actualizaciones instantáneas a través de WebSockets',
      '📁 Arquitectura modular de REST API',
      '🗄️ Almacenamiento eficiente de datos con MongoDB',
      '🚀 Interfaz moderna desarrollada con React y TypeScript',
      '🔄 Gestión de estado sin fisuras con custom hooks',
      '🎨 Diseño totalmente responsivo para todos los dispositivos',
    ],
    linkDemo: 'https://remote-sessions-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/remote-sessions-react',
  },
  {
    title: 'Monopoly - Juego de mesa digital basado en Vue.js',
    tags: [
      'Web Game',
      'Vue.js',
      'Vite',
      'JavaScript',
      'Game Development',
      'WebSockets',
      'State Management',
      'UI/UX',
      'Multiplayer',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1661077030/myPortfolio/ypvbcwolwot13zpj83m1.png',
    ],
    videoUrl: '',
    description:
      'Monopoly es una adaptación digital moderna del clásico juego de mesa Monopoly, desarrollada con Vue.js y Vite. El juego soporta multijugador en tiempo real a través de WebSockets, cuenta con modales interactivos, gestión dinámica del tablero y elementos de interfaz responsivos. Los jugadores pueden comprar propiedades, intercambiar activos y competir en una experiencia digital inmersiva.',
    features: [
      '🎲 Juego de Monopoly completamente interactivo',
      '🌐 Soporte multijugador mediante WebSockets',
      '🛠️ Gestión dinámica del tablero con administración personalizada de casillas',
      '💳 Tarjetas de propiedad y transacciones entre jugadores',
      '📊 Gestión de estado fluida con Vuex',
      '⚡ Rendimiento rápido gracias a Vite y renderizado optimizado',
      '🎨 Diseño de interfaz moderno y responsivo',
      '🔄 Actualizaciones en vivo para movimientos y eventos de jugadores',
    ],
    linkDemo: 'https://github.com/shlominugarker/monoploly-vue.js',
    linkGitHub: 'https://github.com/shlomiNugarker/monopoly-demo/#/',
  },
  {
    title:
      'Ultimate Meme Generator - Aplicación web definitiva para crear memes',
    tags: [
      'Web Application',
      'JavaScript',
      'HTML',
      'CSS',
      'Canvas',
      'Image Processing',
      'UI/UX',
      'Local Storage',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741339981/myPortfolio/b5ot6xjlgir4baq0fz62.jpg',
    ],
    videoUrl: '',
    description:
      'Ultimate Meme Generator es una aplicación web que permite a los usuarios crear y personalizar memes de forma sencilla. Los usuarios pueden seleccionar una imagen de una amplia galería, añadir múltiples capas de texto, ajustar los estilos y descargar sus creaciones como imágenes. La aplicación también soporta el almacenamiento de proyectos en Local Storage para futuras ediciones.',
    features: [
      '🖼️ Amplia galería de imágenes para memes',
      '✏️ Varias capas de texto personalizables',
      '📏 Ajuste de tamaño, posición y alineación del texto',
      '💾 Guardado de proyectos de memes en Local Storage',
      '📥 Descarga de memes en formato de imagen',
      '🎨 Interfaz de usuario intuitiva y responsiva',
      '⚡ Renderizado optimizado con la API de Canvas de HTML',
    ],
    linkDemo:
      'https://shlominugarker.github.io/ultimate-meme-generator-sprint-2/',
    linkGitHub:
      'https://github.com/shlomiNugarker/ultimate-meme-generator-sprint-2',
  },
]

const projectsWithDynamicIds = projects.map((project, index) => ({
  id: index + 1,
  ...project,
}))

export default projectsWithDynamicIds
