const projects = [
  {
    title: 'Travelsdin - The Ultimate Social Network for Travelers',
    tags: [
      'JavaScript (ES6)',
      'MongoDB',
      'React.js',
      'Redux',
      'Rest API',
      'Node.js',
      'Live Chat',
      'Socket.io',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1662386727/ctivc99rxpjymdn0za1n.png',
    ],
    videoUrl: 'https://youtu.be/HUv5xN5qTS4',
    description:
      'Travelsdin is a modern social platform designed for travelers to connect, share experiences, and plan adventures together. With real-time messaging and an intuitive interface, it revolutionizes how travelers interact online.',
    features: [
      'User authentication with JWT (Signup/Login)',
      'Dynamic post feed with infinite scrolling',
      'Real-time chat with WebSockets',
      'Likes, comments, and replies on posts',
      'Friend connection system with requests & approvals',
      'Profile management with image upload',
      'Interactive map with user locations',
      'Notification system for likes, comments, and connections',
      'Secure REST API with Express.js',
      'Cloudinary integration for image hosting',
    ],
    linkDemo: 'https://travelsdin-express-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/Social-Network-Front-',
  },
  {
    title: 'Taskday - Smart Project Management & Collaboration',
    tags: [
      'MongoDB',
      'JavaScript (ES6)',
      'Rest API',
      'Socket.io',
      'Vue.js',
      'SCSS',
      'Vuex',
      'MVC',
      'Single Page Application',
      'Drag and Drop',
      'Node.js',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1660916126/myPortfolio/qdtzolm9ldd5qlquq2aj.png',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=49DkbR-cJis',
    description:
      'Taskday is an intelligent project management system that enhances teamwork with real-time updates, task tracking, and a user-friendly drag-and-drop interface. Designed for maximum efficiency and productivity.',
    features: [
      'Task board management (CRUD)',
      'Real-time task updates using WebSockets',
      'Middleware for security and access control',
      'User-friendly task management interface',
    ],
    linkDemo: 'https://taskday-monday-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/sprint-4',
  },
  {
    title: 'AstroMind-AI - Smart AI-Powered Assistant',
    tags: [
      'AI',
      'Machine Learning',
      'React',
      'Vite',
      'TypeScript',
      'Node.js',
      'Express',
      'MongoDB',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1740232455/ax7kjnkrg75ptdatwvrf.png',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=Ypg4isxvXpk',
    description:
      'AstroMind-AI is a next-generation AI-powered assistant that seamlessly integrates with machine learning models to boost productivity, automate workflows, and provide deep insights in real time.',
    features: [
      'Integration with OpenAI API for AI-generated astrological insights',
      'Advanced user authentication system with JWT',
      'Multilingual support (Hebrew & English) using i18n',
      'Smart chatbot with real-time interaction and responsive UI',
      'Secure connection to MongoDB database',
      'Modern user interface built with React and Tailwind CSS',
      'Data security with advanced role-based access control',
      'User management with different access levels (Admin / User)',
    ],
    linkDemo: 'https://astromind-ai.up.railway.app/#/',
    linkGitHub: 'https://github.com/shlomiNugarker/AstroMind-AI',
  },
  {
    title: 'ShareJSON - Modern Platform for JSON Management and Sharing',
    tags: [
      'React.js',
      'TypeScript',
      'Tailwind CSS',
      'Framer Motion',
      'REST API',
      'JSON Schema',
      'i18n',
      'Dark Mode',
      'Node.js',
      'Express',
      'MongoDB',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1742991355/myPortfolio/0705502d-e8f0-4414-a830-3ff0e5601a71.png',
    ],
    videoUrl: '',
    description:
      'ShareJSON is an innovative platform for managing, validating, and sharing JSON data. With powerful schema management, intuitive editing tools, and seamless collaboration features, it simplifies working with structured data for developers and teams.',
    features: [
      'User authentication with secure login/registration',
      'Dark mode and RTL language support',
      'JSON schema creation and management',
      'Dynamic field validation based on schemas',
      'Shareable JSON data via secure links',
      'Advanced permissions and access controls',
      'Comprehensive REST API for integration',
      'Real-time validation and error checking',
      'Version history and change tracking',
      'Responsive design for desktop and mobile',
      'Multi-language interface with i18n support',
      'Interactive JSON visualization tools',
    ],
    linkDemo: 'https://share-jason-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/share-jason',
    allowIframe: true,
  },
  {
    title: 'Chess Masters - Multiplayer Chess with Live Chat',
    tags: [
      'TypeScript',
      'React',
      'Redux Toolkit',
      'Node.js',
      'Live Chat',
      'MongoDB',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1668701783/myPortfolio/dg6pkn0oxvpgrtjn998y.png',
    ],
    videoUrl: 'https://youtu.be/I90vJUsZzFU',
    description:
      'An interactive multiplayer chess game with real-time chat and smooth gameplay. Designed for chess enthusiasts, it offers a competitive and engaging environment with a sleek, responsive interface.',
    features: [
      'Checkmate and Castling support',
      'Modern design with SCSS',
      'React + TypeScript-based',
    ],
    linkDemo: 'https://chess-v2-backend-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/Chess-V2-React',
  },
  {
    title: 'Dynamic CMS Website Template with Next.js & Tailwind',
    tags: [
      'JavaScript (ES6)',
      'Next.js',
      'React.js',
      'Tailwind CSS',
      'Responsive Design',
      'CMS Functionality',
      'Form Validation',
      'Framer Motion',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1747122912/myPortfolio/297d5b31-0902-4921-a3ca-4f6dabc28bd0.png',
    ],
    videoUrl: '',
    description:
      'This project is a dynamic, customizable CMS front-end built with Next.js and Tailwind CSS. Designed for small businesses, agencies, or personal portfolios, it allows easy content management through modular sections, reusable components, and structured layout.',
    features: [
      'Built with Next.js and React for fast performance and SSR',
      'Styled with Tailwind CSS for flexible and clean UI',
      'Modular page components like Hero, About, Contact, and Packages',
      'Form system with validation and success feedback',
      'Admin content section manager (add, edit, rearrange blocks)',
      'Animation support using Framer Motion for interactive UX',
      'Clear project structure with reusable components',
      'Supports responsive design across devices',
      'Easily extendable to work with headless CMS backends',
      'Includes setup guides and theming documentation',
    ],
    linkDemo: 'https://demo-app-ochre-six.vercel.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/demo-cms-main',
  },
  {
    title: 'Remote Sessions - Live Code Collaboration Platform',
    tags: [
      'Web Application',
      'React',
      'TypeScript',
      'Node.js',
      'Express',
      'MongoDB',
      'WebSockets',
      'JWT Authentication',
      'Real-Time Collaboration',
      'Code Editor',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1673381405/myPortfolio/cztl69dtpc1xxt5j6sf0.png',
    ],
    videoUrl: '',
    description:
      'Remote Sessions is a web-based platform enabling real-time code collaboration and remote programming sessions. Multiple users can edit code simultaneously with live updates powered by WebSockets. Built with React and TypeScript on the frontend, and Node.js with Express and MongoDB on the backend, it offers a seamless experience for collaborative development.',
    features: [
      '💻 Real-time collaborative code editing',
      '🔐 Secure user authentication using JWT',
      '⚡ Instant updates via WebSockets',
      '📁 Modular REST API architecture',
      '🗄️ Efficient data storage with MongoDB',
      '🚀 Modern UI built with React and TypeScript',
      '🔄 Seamless state management with custom hooks',
      '🎨 Fully responsive design for all devices',
    ],
    linkDemo: 'https://remote-sessions-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/remote-sessions-react',
  },
  {
    title: 'Payload CMS-Powered Business Website',
    tags: [
      'Next.js',
      'TypeScript',
      'Payload CMS',
      'Tailwind CSS',
      'MongoDB',
      'Docker',
      'Vercel',
      'Lexical',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1745521786/myPortfolio/a11fd6e9-477a-4e5d-a7da-fdcdf5144517.png',
    ],
    videoUrl: '',
    description:
      'A modern content-driven platform powered by Payload CMS. Includes a dynamic block-based page builder, blog system, contact forms, global header/footer management, full SEO support, and deployment-ready setup using Docker and Vercel.',
    features: [
      'Payload CMS integration with MongoDB database',
      'Advanced Lexical Rich Text editor for content',
      'Dynamic block-based page building system',
      'Full blog with categories, posts, and featured content',
      'Global Header and Footer content managed via CMS',
      'Custom API routes (Contact, Newsletter, Guides)',
      'Fully responsive design using Tailwind CSS',
      'Cloud-native image storage with Vercel Blob',
      'Dockerized local development setup',
      'Auto-generated redirects, Meta tags, and OpenGraph support',
    ],
    linkDemo: 'https://payload-cms-website-shlomi.vercel.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/payload-website',
  },
]

const projectsWithDynamicIds = projects.map((project, index) => ({
  id: index + 1,
  ...project,
}))

export default projectsWithDynamicIds
