const projects = [
  {
    title: 'Travelsdin - Das ultimative soziale Netzwerk für Reisende',
    tags: [
      'JavaScript (ES6)',
      'MongoDB',
      'React.js',
      'Redux',
      'Rest API',
      'Node.js',
      'Live Chat',
      'Socket.io',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1662386727/ctivc99rxpjymdn0za1n.png',
    ],
    videoUrl: 'https://youtu.be/HUv5xN5qTS4',
    description:
      'Travelsdin ist eine moderne Social-Plattform, die für Reisende entwickelt wurde, um sich zu vernetzen, Erfahrungen auszutauschen und gemeinsame Abenteuer zu planen. Mit Echtzeit-Messaging und einer intuitiven Benutzeroberfläche revolutioniert sie die Art und Weise, wie Reisende online interagieren.',
    linkDemo: 'https://travelsdin-express-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/Social-Network-Front-',
  },
  {
    title: 'Taskday - Intelligentes Projektmanagement und Zusammenarbeit',
    tags: [
      'MongoDB',
      'JavaScript (ES6)',
      'Rest API',
      'Socket.io',
      'Vue.js',
      'SCSS',
      'Vuex',
      'MVC',
      'Single Page Application',
      'Drag and Drop',
      'Node.js',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1660916126/myPortfolio/qdtzolm9ldd5qlquq2aj.png',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=49DkbR-cJis',
    description:
      'Taskday ist ein intelligentes Projektmanagement-System, das die Teamarbeit durch Echtzeit-Updates, Aufgabenverfolgung und eine benutzerfreundliche Drag-and-Drop-Oberfläche verbessert. Es wurde für maximale Effizienz und Produktivität entwickelt.',
    linkDemo: 'https://taskday-monday-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/sprint-4',
  },
  {
    title: 'Chess Masters - Multiplayer-Schach mit Live-Chat',
    tags: [
      'TypeScript',
      'React',
      'Redux Toolkit',
      'Node.js',
      'Live Chat',
      'MongoDB',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1668701783/myPortfolio/dg6pkn0oxvpgrtjn998y.png',
    ],
    videoUrl: 'https://youtu.be/I90vJUsZzFU',
    description:
      'Ein interaktives Multiplayer-Schachspiel mit Live-Chat und flüssigem Gameplay. Entwickelt für Schachliebhaber, bietet es eine wettbewerbsfähige und fesselnde Umgebung mit einer eleganten, responsiven Benutzeroberfläche.',
    linkDemo: 'https://chess-v2-backend-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/Chess-V2-React',
  },
  {
    title: 'AstroMind-AI - Intelligenter AI-gesteuerter Assistent',
    tags: [
      'AI',
      'Machine Learning',
      'React',
      'Vite',
      'TypeScript',
      'Node.js',
      'Express',
      'MongoDB',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1740232455/ax7kjnkrg75ptdatwvrf.png',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=Ypg4isxvXpk',
    description:
      'AstroMind-AI ist ein Assistent der nächsten Generation, der auf künstlicher Intelligenz basiert und sich nahtlos in Machine Learning-Modelle integriert, um die Produktivität zu steigern, Arbeitsabläufe zu automatisieren und in Echtzeit tiefgehende Einblicke zu bieten.',
    linkDemo: 'https://astromind-ai.up.railway.app/#/',
    linkGitHub: 'https://github.com/shlomiNugarker/AstroMind-AI',
  },
  {
    title: 'Tetris - Klassisches Spiel in TypeScript',
    tags: [
      'Game Development',
      'TypeScript',
      'Canvas API',
      'Vite',
      'Vanilla JavaScript',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741333933/hcft00ztvoddagepecqd.jpg',
    ],
    videoUrl: '',
    description:
      'Ein modernes, leichtgewichtiges Tetris-Spiel, entwickelt mit TypeScript und der Canvas API. Das Spiel zeichnet sich durch fließende Animationen, dynamische Schwierigkeitsanpassung und eine saubere Benutzeroberfläche aus.',
    linkDemo: 'https://shlominugarker.github.io/tetris-vannila-ts/',
    linkGitHub: 'https://github.com/shlomiNugarker/tetris-vannila-ts',
  },
  {
    title: 'Todo List - Aufgabenverwaltungs-App',
    tags: [
      'Task Management',
      'React',
      'Vite',
      'TypeScript',
      'Tailwind CSS',
      'LocalStorage',
      'State Management',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741334749/m7tjy3w64of8myg4zzhf.jpg',
    ],
    videoUrl: '',
    description:
      'Eine moderne und effiziente Todo-List-Anwendung, entwickelt mit React und TypeScript. Die App ermöglicht die Erstellung, Bearbeitung und Filterung von Aufgaben nach Zuständigen und Priorität sowie die lokale Speicherung.',
    linkDemo: 'https://shlominugarker.github.io/todo-list-react-application/',
    linkGitHub: 'https://github.com/shlomiNugarker/todo-list-react-application',
  },
  {
    title: 'Jpeg-to-PDF - Bilder in PDF konvertieren mit OCR',
    tags: [
      'OCR',
      'Image Processing',
      'React',
      'Next.js',
      'Tailwind CSS',
      'TypeScript',
      'Node.js',
      'Express',
      'Tesseract.js',
      'pdf-lib',
      'MongoDB',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741335295/q9yen9arwacqz2l1m7if.jpg',
    ],
    videoUrl: '',
    description:
      'Jpeg-to-PDF ist eine fortschrittliche Webanwendung zur Umwandlung von Bildern in PDF-Dateien. Sie unterstützt OCR-Technologie über Tesseract.js, wodurch Text aus Bildern extrahiert und in das erstellte PDF eingebettet wird. Die Anwendung wurde mit Next.js für das Frontend und Node.js mit Express für das Backend entwickelt, sodass Benutzer Bilder hochladen, in hochwertige PDFs umwandeln und die Ergebnisse nahtlos herunterladen können.',
    features: [
      '💡 Schnelle und effiziente Umwandlung von Bildern in PDFs',
      '🔍 OCR-Unterstützung zur Texterkennung in Bildern',
      '📤 Benutzerfreundliche Oberfläche zum Hochladen von Bildern',
      '📥 Herunterladen der generierten PDF-Datei',
      '🗑️ Automatische Bereinigung temporärer Dateien nach der Verarbeitung',
      '🚀 Modernes Frontend mit Next.js und Tailwind CSS',
      '⚙️ Robustes Backend mit Express und MongoDB',
    ],
    linkDemo: 'https://image-to-pdf-free.vercel.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/jpeg-to-pdf-nextjs',
  },
  {
    title: 'WhatsApp Clone - Echtzeit-Chat-Anwendung',
    tags: [
      'Real-time Communication',
      'Chat Application',
      'Angular',
      'TypeScript',
      'SCSS',
      'Node.js',
      'Express',
      'MongoDB',
      'Socket.io',
      'JWT Authentication',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741336608/mrx5om1pnkozrla5bpsm.jpg',
    ],
    videoUrl: '',
    description:
      'WhatsApp Clone ist eine voll ausgestattete Chat-Anwendung, die die Kernfunktionen von WhatsApp nachbildet und Echtzeit-Kommunikation zwischen Benutzern ermöglicht. Entwickelt mit Angular für das Frontend und Node.js mit Express für das Backend, nutzt es MongoDB zur Datenspeicherung und Socket.io für Echtzeit-Updates. Die Anwendung beinhaltet Benutzerauthentifizierung, Nachrichtenverschlüsselung und eine intuitive Chat-Oberfläche.',
    features: [
      '💡 Sichere und Echtzeit-Kommunikation mit Socket.io',
      '🔐 Benutzerauthentifizierung mit JWT',
      '📤 Nahtloses Benutzerregistrierungs- und Login-System',
      '📥 Chat-Verlauf und Benutzerdaten-Speicherung mit MongoDB',
      '🎨 Modernes UI, entwickelt mit Angular und SCSS',
      '🚀 Skalierbares und effizientes Backend mit Express.js',
      '🗑️ Automatische Bereinigung temporärer Chat-Logs',
    ],
    linkDemo: 'https://achchhapp.onrender.com/',
    linkGitHub: 'https://github.com/shlomiNugarker/whatsapp-clone-angular',
  },
  {
    title: 'Snake Game - Klassisches Browser-Spiel',
    tags: [
      'Web Game',
      'JavaScript',
      'HTML',
      'CSS',
      'Vanilla JS',
      'Game Development',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741336903/hwdhzecww9joudezoyrn.jpg',
    ],
    videoUrl: '',
    description:
      'Ein klassisches Snake-Spiel, entwickelt mit reinem JavaScript (Vanilla JS) und direkt im Browser spielbar. Der Spieler steuert die Schlange mit den Pfeiltasten und versucht, so viel Nahrung wie möglich zu fressen, ohne die Bildschirmränder oder den eigenen Körper zu berühren. Das Spiel verfügt über ein Punktesystem, Soundeffekte und steigende Geschwindigkeit, wenn die Schlange wächst.',
    features: [
      '🎮 Klassisches Snake-Spiel-Erlebnis',
      '⌨️ Steuerung mit Pfeiltasten für flüssiges Gameplay',
      '🔊 Soundeffekte für Bewegung und Fressgeräusche',
      '📈 Echtzeit-Punktverfolgung',
      '🚀 Leichter und erweiterbarer Vanilla JS-Code',
      '🎨 Einfaches CSS-Styling für ein sauberes Benutzererlebnis',
    ],
    linkDemo: 'https://shlominugarker.github.io/snake-vannila-js/',
    linkGitHub: 'http://github.com/shlomiNugarker/snake-vannila-js',
  },
  {
    title: 'Checkers Game - Klassisches Brettspiel auf Basis von Vue.js',
    tags: [
      'Web Game',
      'Vue.js',
      'TypeScript',
      'Vite',
      'CSS',
      'Game Development',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741337246/gxxqlgeuaqbk67qrdhge.jpg',
    ],
    videoUrl: '',
    description:
      'Ein klassisches Checkers-Spiel, entwickelt mit Vue.js und TypeScript, mit moderner Benutzeroberfläche und vollständiger Einhaltung der Standardregeln.',
    features: [
      '🎮 Interaktives Checkers-Spiel mit intuitiver Benutzeroberfläche',
      '🔄 Zwei-Spieler-Modus für wettbewerbsfähiges Spiel',
      '🎨 Moderne, mit Vue.js entwickelte Oberfläche',
      '🖱️ Fließende Benutzererfahrung mit Animationen',
      '📈 Punktverfolgung und Zughistorie',
      '🚀 Optimiert mit Vite für schnelles Laden und hohe Leistung',
    ],
    linkDemo: 'https://shlominugarker.github.io/checkers-vue-js/',
    linkGitHub: 'https://github.com/shlomiNugarker/checkers-vue-js',
  },
  {
    title: 'Sudoku Game - Fortschrittliches Web-Spiel auf Basis von TypeScript',
    tags: [
      'Web Game',
      'TypeScript',
      'HTML',
      'CSS',
      'Vite',
      'Game Development',
      'Local Storage',
      'Algorithmic Optimization',
      'OOP',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741337655/szym9lrspw75mtysoya2.jpg',
    ],
    videoUrl: '',
    description:
      'Ein funktionsreiches Sudoku-Spiel, entwickelt mit TypeScript und optimiert für schnelles, nahtloses Gameplay im Browser. Das Spiel beinhaltet die Validierung von Zügen in Echtzeit, dynamisch generierte Rätsel, die Auswahl des Schwierigkeitsgrads und ein elegantes, modernes UI. Implementiert unter Verwendung von objektorientierten Programmierprinzipien, gewährleistet es eine skalierbare und effiziente Architektur. Der Fortschritt wird automatisch über Local Storage gespeichert, sodass Spieler ihr Spiel jederzeit fortsetzen können.',
    features: [
      '🎮 Vollständig interaktives und dynamisches Sudoku-Gameplay',
      '🔢 Intelligente Brettgenerierung mit einstellbarem Schwierigkeitsgrad',
      '✔️ Echtzeit-Validierung der Züge und Korrektheitsprüfungen',
      '💾 Automatisches Speichern des Fortschritts über Local Storage',
      '📊 Mehrere Schwierigkeitsgrade: Einfach, Mittel, Schwer, Experte',
      '⚡ Optimierte Leistung mit Vite für schnelles Laden',
      '🖥️ Responsives Design mit einem adaptiven Rasterlayout',
      '🎨 Elegante Benutzeroberfläche mit anpassbaren Themes (Hell & Dunkel)',
      '🚀 Skalierbare Architektur unter Verwendung von TypeScript und OOP-Prinzipien',
    ],
    linkDemo: 'https://shlominugarker.github.io/sudoku-vannila-ts/',
    linkGitHub: 'https://github.com/shlomiNugarker/sudoku-vannila-ts',
  },
  {
    title: '2D Action Game - Spielentwicklung mit TypeScript',
    tags: [
      'Game Development',
      'TypeScript',
      'Canvas',
      'Web Game',
      'Webpack',
      'Object-Oriented Programming',
      'Animations',
      'Physics',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741337983/fyerm3gsrfvkzdungm6j.jpg',
    ],
    videoUrl: '',
    description:
      'Ein schnelles 2D-Action-Spiel, entwickelt mit TypeScript und konzipiert für den direkten Betrieb im Browser. Das Spiel bietet einen vom Spieler gesteuerten Charakter, der sich bewegen, springen und Gegner angreifen kann. Mit fortschrittlichen physikalischen Interaktionen, Kollisionsanimationen und mehrschichtigen Hintergrundeinstellungen demonstriert es modernste Techniken der Spieleentwicklung mit modernem JavaScript und OOP-Prinzipien.',
    features: [
      '🎮 Dynamisches 2D-Action-Gameplay mit vollständiger Spielersteuerung',
      '🕹️ Tastaturgesteuerte Bewegung mit Echtzeit-Physik',
      '👾 Fortschrittliches KI-System für Gegner mit unterschiedlichen Angriffsmustern',
      '💥 Kollisionsdetektion und partikelbasierte visuelle Effekte',
      '🖥️ Mehrschichtige Parallax-Hintergründe für ein intensives Erlebnis',
      '⚡ Optimierte Spielschleife für flüssige Leistung',
      '🎨 Vollständig animierte Spieler- und Gegner-Sprites',
      '🚀 Skalierbare und modulare Architektur unter Verwendung von TypeScript und OOP',
    ],
    linkDemo: 'https://shlominugarker.github.io/game-development-tutorial/',
    linkGitHub: 'https://github.com/shlomiNugarker/game-development-tutorial',
  },
  {
    title: 'Minesweeper - Das klassische Minesweeper-Spiel in JavaScript',
    tags: [
      'Web Game',
      'JavaScript',
      'HTML',
      'CSS',
      'Game Development',
      'Algorithms',
      'UI/UX',
      'Animations',
      'Audio Effects',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741338893/noxnpv9mpekeoyilpibj.jpg',
    ],
    videoUrl: '',
    description:
      'Eine modernisierte Version des klassischen Minesweeper-Spiels, entwickelt mit JavaScript, HTML und CSS. Es bietet eine dynamische Spielfeldgenerierung, intelligente Mechanismen zum Aufdecken von Zellen, Minenmarkierung sowie Gewinn- und Verlustbedingungen und interaktive Soundeffekte für ein verbessertes Spielerlebnis.',
    features: [
      '🎮 Klassisches Minesweeper-Gameplay mit modernem Design',
      '🛠️ Anpassbare Spielfeldgröße und Schwierigkeitsgrade',
      '🔍 Intelligentes Aufdecken von Zellen, um leere Bereiche zu enthüllen',
      '🚩 Markierungssystem zur Kennzeichnung verdächtiger Minen',
      '🎵 Interaktive Soundeffekte für ein intensives Erlebnis',
      '⏳ Echtzeit-Timer zur Verfolgung der Spieldauer',
      '⚡ Fließende Animationen und responsives Design',
      '🚀 Optimierte Spiel-Logik für schnelle Leistung',
    ],
    linkDemo: 'https://shlominugarker.github.io/minesweeper-sprint-1/',
    linkGitHub: 'https://github.com/shlomiNugarker/minesweeper-sprint-1',
  },
  {
    title: 'Remote Sessions - Plattform für Live-Code-Kollaboration',
    tags: [
      'Web Application',
      'React',
      'TypeScript',
      'Node.js',
      'Express',
      'MongoDB',
      'WebSockets',
      'JWT Authentication',
      'Real-Time Collaboration',
      'Code Editor',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1673381405/myPortfolio/cztl69dtpc1xxt5j6sf0.png',
    ],
    videoUrl: '',
    description:
      'Remote Sessions ist eine webbasierte Plattform, die Echtzeit-Code-Kollaboration und Remote-Programmiersitzungen ermöglicht. Mehrere Benutzer können gleichzeitig Code bearbeiten, unterstützt durch Live-Updates via WebSockets. Entwickelt mit React und TypeScript im Frontend sowie Node.js mit Express und MongoDB im Backend, bietet es ein nahtloses Erlebnis für kollaborative Entwicklung.',
    features: [
      '💻 Echtzeit-Kollaboration beim Code-Schreiben',
      '🔐 Sichere Benutzerauthentifizierung mit JWT',
      '⚡ Sofortige Updates via WebSockets',
      '📁 Modulare REST API-Architektur',
      '🗄️ Effiziente Datenspeicherung mit MongoDB',
      '🚀 Modernes UI, entwickelt mit React und TypeScript',
      '🔄 Nahtloses State-Management mit custom hooks',
      '🎨 Vollständig responsives Design für alle Geräte',
    ],
    linkDemo: 'https://remote-sessions-production.up.railway.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/remote-sessions-react',
  },
  {
    title: 'Monopoly - Digitales Brettspiel auf Basis von Vue.js',
    tags: [
      'Web Game',
      'Vue.js',
      'Vite',
      'JavaScript',
      'Game Development',
      'WebSockets',
      'State Management',
      'UI/UX',
      'Multiplayer',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1661077030/myPortfolio/ypvbcwolwot13zpj83m1.png',
    ],
    videoUrl: '',
    description:
      'Monopoly ist eine moderne digitale Adaption des klassischen Brettspiels Monopoly, entwickelt mit Vue.js und Vite. Mit Unterstützung von Echtzeit-Multiplayer via WebSockets, interaktiven Modals, dynamischem Spielfeldmanagement und responsiven UI-Elementen können Spieler Immobilien kaufen, Vermögenswerte tauschen und in ein intensives digitales Monopoly-Erlebnis eintauchen.',
    features: [
      '🎲 Vollständig interaktives Monopoly-Brettspiel',
      '🌐 Multiplayer-Unterstützung via WebSockets',
      '🛠️ Dynamisches Spielfeld mit individueller Kachelverwaltung',
      '💳 Eigentumskarten und Spielertransaktionen',
      '📊 Nahtloses State-Management mit Vuex',
      '⚡ Schnelle Leistung dank Vite und optimiertem Rendering',
      '🎨 Modernes und responsives UI-Design',
      '🔄 Live-Updates für Spielerbewegungen und Ereignisse',
    ],
    linkDemo: 'https://github.com/shlomiNugarker/monoploly-vue.js',
    linkGitHub: 'https://github.com/shlomiNugarker/monopoly-demo/#/',
  },
  {
    title: 'Ultimate Meme Generator - Ultimative Meme-Generator Web-App',
    tags: [
      'Web Application',
      'JavaScript',
      'HTML',
      'CSS',
      'Canvas',
      'Image Processing',
      'UI/UX',
      'Local Storage',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741339981/myPortfolio/b5ot6xjlgir4baq0fz62.jpg',
    ],
    videoUrl: '',
    description:
      'Ultimate Meme Generator ist eine webbasierte Anwendung, die es Nutzern ermöglicht, mühelos Memes zu erstellen und anzupassen. Benutzer können ein Bild aus einer umfangreichen Galerie auswählen, mehrere Textebenen hinzufügen, Textstile anpassen und ihre Kreationen als Bilder herunterladen. Die App unterstützt zudem das Speichern von Projekten in Local Storage für spätere Bearbeitungen.',
    features: [
      '🖼️ Umfangreiche Meme-Bildergalerie',
      '✏️ Mehrere anpassbare Textebenen',
      '📏 Einstellbare Textgröße, Position und Ausrichtung',
      '💾 Meme-Projekte in Local Storage speichern',
      '📥 Memes als Bilddateien herunterladen',
      '🎨 Intuitive und responsive Benutzeroberfläche',
      '⚡ Optimierter Rendering mit der HTML Canvas API',
    ],
    linkDemo:
      'https://shlominugarker.github.io/ultimate-meme-generator-sprint-2/',
    linkGitHub:
      'https://github.com/shlomiNugarker/ultimate-meme-generator-sprint-2',
  },
  {
    title: 'Benutzerdefiniertes CMS mit Next.js',
    tags: [
      'Next.js',
      'TypeScript',
      'PostgreSQL',
      'Drizzle ORM',
      'Tailwind CSS',
      'NextAuth.js',
      'Cloudinary',
      'Docker',
    ],
    imgs: [
      'https://res.cloudinary.com/duajg3ah1/image/upload/v1741512665/myPortfolio/40f5fc4f-5a40-49d1-b070-9652e9e73d75.png',
    ],
    videoUrl: '',
    description:
      'Ein dynamisches CMS, das mit Next.js und Drizzle ORM entwickelt wurde. Unterstützt die Verwaltung von Seiten, die Bearbeitung von Inhalten über eine flexible Admin-Oberfläche und die Speicherung von Medien in Cloudinary.',
    linkDemo: 'https://my-site-data-api.vercel.app/',
    linkGitHub: 'https://github.com/shlomiNugarker/nextjs-with-costum-cms',
    features: [
      'Dynamische Inhaltsverwaltung mit tabellenbasierter Struktur',
      'Benutzer-Authentifizierung mit NextAuth',
      'Interaktive Admin-Oberfläche mit Tailwind CSS',
      'Medienverwaltung mit Cloudinary',
      'Bereitstellungsunterstützung mit Docker',
      'Datenverwaltung über REST API',
    ],
  },
]

const projectsWithDynamicIds = projects.map((project, index) => ({
  id: index + 1,
  ...project,
}))

export default projectsWithDynamicIds
